# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nippon_koei_livemap.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap

from ui.mplwidget import MplWidget
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import matplotlib.pyplot as plt
import random


class Ui_MainWindow(object):
    '''
    Auto generated by PyQT toolkit
    '''

    def setupUi(self, MainWindow):
        self.figure = plt.figure()
        self.mpl = MplWidget()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1185, 798)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.widgetLiveMap = MplWidget(self.centralwidget)
        self.widgetLiveMap.setGeometry(QtCore.QRect(0, 240, 941, 501))
        self.widgetLiveMap.setObjectName("widgetLiveMap")
        self.widgetLiveMap.canvas = FigureCanvas(self.figure)

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 0, 1071, 151))
        self.label.setObjectName("label")

        self.label.setPixmap(
            QPixmap("logo_nk_blue_transparentR.png"))
        self.label.setScaledContents(True)

        self.buttonHeatMap = QtWidgets.QPushButton(self.centralwidget)
        self.buttonHeatMap.setGeometry(QtCore.QRect(1010, 650, 161, 91))
        self.buttonHeatMap.setObjectName("buttonHeatMap")
        self.labelTitle = QtWidgets.QLabel(self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(50, 180, 300, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(26)
        self.labelTitle.setFont(font)
        self.labelTitle.setObjectName("labelTitle")
        self.labelStatus = QtWidgets.QLabel(self.centralwidget)
        self.labelStatus.setGeometry(QtCore.QRect(1010, 240, 161, 391))
        self.labelStatus.setTextFormat(QtCore.Qt.RichText)
        self.labelStatus.setAlignment(
            QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.labelStatus.setWordWrap(True)
        self.labelStatus.setIndent(0)
        self.labelStatus.setObjectName("labelStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1185, 21))
        self.menubar.setObjectName("menubar")
        self.menuInfo = QtWidgets.QMenu(self.menubar)
        self.menuInfo.setObjectName("menuInfo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        MainWindow.setStyleSheet("background-color: white;")
        self.actionShow_Log_History = QtWidgets.QAction(MainWindow)
        self.actionShow_Log_History.setObjectName("actionShow_Log_History")
        self.actionHelp = QtWidgets.QAction(MainWindow)
        self.actionHelp.setObjectName("actionHelp")
        self.menuInfo.addAction(self.actionShow_Log_History)
        self.menuInfo.addAction(self.actionHelp)
        self.menubar.addAction(self.menuInfo.menuAction())

        self.buttonHeatMap.clicked.connect(
            self.buttonChangeListener)  # activateLoop

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Nippon Koei Display"))
        self.label.setPixmap(
            QPixmap("logo_nk_blue_transparentR.png"))

        # Formerly "View Heat Map"
        self.buttonHeatMap.setText(_translate("MainWindow", "Heat Map"))
        self.labelTitle.setText(_translate("MainWindow", "Live Map View"))
        self.labelStatus.setText(_translate(
            "MainWindow", "<html><head/><body><p>Status Message</p></body></html>"))
        self.menuInfo.setTitle(_translate("MainWindow", "Info"))
        self.actionShow_Log_History.setText(
            _translate("MainWindow", "Show Log"))
        self.actionHelp.setText(_translate("MainWindow", "Help"))

    '''
    on click listener, calls heatmap plot function on button press
    '''

    def buttonChangeListener(self):

        self.widgetLiveMap.plotHeatMapMode()
